project_id = "sbtdubgxwpymeatrpgwm"

[functions.paystack]
verify_jwt = false

[functions.ai-tutor]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.milestone-emails]
verify_jwt = false
