-- Update Week 4 title and description
UPDATE public.weeks 
SET title = 'AI-Powered Website Creation & Publishing: From Concept to Live Site',
    description = 'Unlock the power of AI to streamline and accelerate every stage of website development, from foundational concepts and content generation to basic coding and online publishing. This week delves into practical applications of modern AI tools, empowering you to create and deploy functional, simple websites with unprecedented efficiency, while understanding the underlying web technologies.'
WHERE id = '7e053e03-8d0e-46d3-8a61-1a2424963591';

-- Update Lesson 1
UPDATE public.lessons SET
  title = 'Demystifying the Web: Architectures, Protocols, and Core Components',
  content = E'Before harnessing AI for web creation, a solid understanding of how the internet and websites fundamentally operate is crucial. Picture the web as a colossal, interconnected network of computers. When you access a website, your web browser (the ''client'') sends a request over the internet to a ''web server'' – a specialized computer designed to host website files and respond to these requests. This communication happens using protocols like HTTP/HTTPS, which dictate how data is formatted and transferred. The server then located the requested files (HTML, CSS, JavaScript, images, etc.) and sends them back to your browser, which interprets and renders them into the visual, interactive webpage you see.\n\nAt the heart of every webpage are three foundational languages: **HTML (HyperText Markup Language)**, which provides the structural backbone and defines content elements like headings, paragraphs, and images; **CSS (Cascading Style Sheets)**, which controls the visual presentation, dictating colors, fonts, layouts, and animations; and **JavaScript**, which adds dynamic interactivity, enabling features like dropdown menus, form validations, and animated elements. Understanding their distinct roles allows for more targeted and effective AI prompting.\n\nBeyond these core languages, ''Hosting'' refers to the service that makes your website''s files accessible 24/7 on a web server, ensuring global reach. ''Domain names'' (e.g., example.com) serve as human-friendly addresses that map to complex IP addresses, guiding users to your hosted website. The **Domain Name System (DNS)** acts like the internet''s phonebook, translating these domain names into the numerical IP addresses that computers use to find each other.\n\nThis client-server model, coupled with the roles of HTML, CSS, JavaScript, hosting, and domains, forms the architectural bedrock of the web. AI tools don''t replace these fundamentals but rather abstract away much of the manual coding and configuration, empowering individuals without deep technical expertise to build and manage online presences more effectively.\n\n**Case Study**: Consider a basic blog. The blog posts themselves are content within HTML tags. The consistent look and feel – the font choices, the header layout, the sidebar styling – are defined by CSS. Interactive elements like a ''Read More'' button expanding text or comment submission forms are powered by JavaScript. All these files are stored on a web server provided by a hosting company, and users access it via a domain name like ''myamazingblog.com''. AI can now generate entire blog post content, draft the HTML/CSS for its layout, and even suggest domain names, simplifying the entire workflow significantly.',
  learning_objective = 'Analyze and articulate the client-server model, the roles of HTML, CSS, and JavaScript, and the functions of hosting and domain names as essential building blocks for any website.',
  practical_task = E'1. **Inspect and Deconstruct**: Open a popular website (e.g., a news site, an e-commerce store) in your browser. Right-click and choose ''Inspect Element'' (or ''Developer Tools''). Navigate through the ''Elements'' tab to identify specific HTML tags. Then, switch to the ''Styles'' pane to see how CSS properties are applied to these elements. 2. **Reflect**: In a short paragraph, explain how understanding the interplay between HTML (structure) and CSS (style) helps in effectively prompting an AI to generate web design components. 3. **Research**: Briefly research the concept of ''responsive web design'' and explain why it''s crucial for modern websites.'
WHERE id = 'f039797b-f414-4208-9740-a15a555bf1e8';

-- Update Lesson 2
UPDATE public.lessons SET
  title = 'Mastering Content Generation: AI for Engaging Website Copy and SEO',
  content = E'Creating compelling and relevant website content is often the most time-consuming yet critical aspect of building an effective online presence. AI tools have revolutionized this process, acting as sophisticated co-writers capable of generating diverse content types with remarkable efficiency. From attention-grabbing headlines and persuasive calls-to-action to comprehensive ''About Us'' narratives, detailed product descriptions, and SEO-optimized blog posts, AI can produce high-quality text tailored to specific needs.\n\nThe key to successful AI content generation lies in crafting precise and detailed prompts. Think of it as providing a brief to a human copywriter: clearly specify your **target audience**, the desired **tone of voice**, the **goals of the content**, and crucial **keywords** for search engine optimization (SEO). For instance, instead of just ''write about coffee,'' prompt: ''Generate an engaging, warm, and sophisticated 2-paragraph description for a new artisanal coffee shop''s homepage, targeting urban professionals. Include keywords like single-origin beans, ethical sourcing, and cozy atmosphere.''\n\nAI''s ability to quickly generate multiple variations is a huge advantage. You can request several options for a headline or a product description, then select the best one or combine elements from different outputs. This iterative process drastically reduces writer''s block and accelerates content development. However, it''s vital to view AI-generated content as a starting point. Always review for accuracy, factual correctness, brand voice consistency, originality, and to infuse it with your unique human touch and perspective.\n\nBeyond direct content creation, AI can assist with content strategy. It can research common questions related to your niche, suggest blog topics, create outlines, and even perform basic keyword analysis to inform your output. Tools like Claude, known for its extensive context window and nuanced understanding, can handle complex content requests, generating detailed narratives or long-form articles that maintain coherence and relevance.\n\n**Case Study**: A small e-commerce startup specializing in handmade jewelry uses AI to generate product descriptions. Instead of laboriously writing each one, they input details like material, inspiration, target demographic, and key features. The AI provides several options, highlighting ethical sourcing and unique design elements. The startup''s team then refines these, adding a personal anecdote about the artisan or a specific styling tip, transforming AI-generated text into uniquely branded content that resonates with their target market.',
  learning_objective = 'Formulate sophisticated prompts to guide AI tools in generating diverse website content, including SEO-optimized text, headlines, and calls-to-action, then evaluate and refine the output for tone, accuracy, and brand consistency.',
  practical_task = E'1. **Business Profile Creation**: Select a specific fictional business. Define its target audience, brand voice, and unique selling propositions. 2. **Prompt Engineering**: Using your chosen AI text generator, craft detailed prompts to generate: Homepage Hero Section Copy (headline + 2-paragraph intro), ''About Us'' Page Content (3-4 paragraphs), and a Product/Service Description (3 paragraphs with call-to-action). 3. **Critique and Refine**: Evaluate the AI output. Identify strengths and weaknesses. Manually edit and improve each section, adding your own human touch. Explain your reasoning for the edits.'
WHERE id = '96c8a094-c0d6-4708-bdcb-b88d7bd0515c';

-- Update Lesson 3
UPDATE public.lessons SET
  title = 'AI in Design and Development: From Wireframes to Code',
  content = E'The evolution of AI in web development extends beyond content to the very structure and styling of websites. AI can now significantly assist in translating conceptual ideas into tangible design elements and even functional code. This capability ranges from generating basic HTML/CSS structures based on natural language descriptions to assisting with intricate UI component design and suggesting optimal layouts for user experience. Tools like **Antigravity** and **Lovable** aim to interpret user intent from prompts, often visually, converting abstract design goals into concrete wireframes, mockups, or even directly implementable front-end code snippets.\n\nImagine describing your desired website layout: ''a clean, minimalist landing page with a full-width hero image, a centered call-to-action button, three feature blocks arranged horizontally, and a footer with social media icons.'' AI can take this textual description and generate the foundational HTML markup and preliminary CSS styling that aligns with your vision. While the initial output might be generic, it provides a robust starting point, allowing you to focus on refinement and customization rather than building from scratch.\n\nAdvanced AI integration in design tools can analyze design patterns, recommend color palettes, suggest typography combinations, and even generate entire sections or components that adhere to modern web standards and accessibility guidelines. Some platforms are exploring the ability to convert sketches or low-fidelity wireframes directly into high-fidelity designs or code. These AI-powered design assistants act as intelligent collaborators, offering solutions and recommendations that enhance both aesthetics and functionality.\n\nFor learning purposes, working with AI-generated code provides an invaluable opportunity to understand the relationship between a prompt, the resulting code, and its visual representation in a browser. By examining the HTML tags and CSS properties generated, you can quickly grasp how different elements are structured and styled. You can then copy this code into a simple text editor or an online code playground (like CodePen or JSFiddle), save it, and open it in your browser to observe the outcome.\n\n**Case Study**: A non-profit organization needed a simple event registration page quickly. Instead of hiring a developer, they used an AI code generator. They prompted: ''Create an event registration page with a title, event description, date, time, location, and a form with fields for name, email, and number of attendees.'' The AI provided the HTML and basic CSS. The team then easily customized the colors and added their event-specific text, launching a functional page within hours.',
  learning_objective = 'Generate and critically evaluate basic HTML and CSS code from AI prompts to construct web page layouts and apply initial styling. Experiment with AI-powered design tools to understand their role in visual design translation and rapid prototyping.',
  practical_task = E'1. **Visual Concept to Code Prompt**: Choose a website layout concept (Portfolio page, E-commerce Product page, or Blog Post page). Write a detailed prompt for an AI code generator specifying desired elements, arrangement, and aesthetic. 2. **Code Generation and Review**: Generate the HTML and basic CSS. Copy into CodePen or JSFiddle. Observe the output. Identify which parts were successfully translated and where the AI fell short. 3. **Refinement**: Make one small manual CSS change (e.g., background color, font size, margin) and observe its effect. Write a brief paragraph explaining the power and limitations of AI in generating web structure and design.'
WHERE id = '098df0f1-3132-45e7-83b9-0ad092752cd1';

-- Update Lesson 4
UPDATE public.lessons SET
  title = 'Bringing Your Vision Live: AI-Assisted Website Publishing and Deployment',
  content = E'The final, exhilarating step in web development is bringing your creation to life: publishing it online for the world to see. This involves selecting a hosting provider and deploying your website files. For the simple, static websites typically generated with AI assistance – those consisting primarily of HTML, CSS, images, and minimal JavaScript without complex server-side processing or databases – numerous user-friendly and often free hosting options are ideal for beginners and small projects.\n\nPopular choices for static site hosting include **GitHub Pages**, which integrates seamlessly if you''re using Git for version control; **Netlify**, known for its excellent developer experience, automatic deployments, and integration with Git repositories; and **Vercel**, another powerful platform optimized for front-end frameworks and static sites. These services typically offer a simple interface for uploading your files or connecting to a repository where your website code resides.\n\nThe deployment process usually involves creating an account, then either uploading your files directly via their dashboard or connecting your hosting service to a Git repository like GitHub. When you push changes to your repository, the hosting service automatically rebuilds and deploys your site, ensuring your live version is always up-to-date. This Continuous Integration/Continuous Deployment (CI/CD) pipeline automates what was once a complex, manual process.\n\nOnce deployed, your website will be assigned a unique URL. You can then share this URL, making your AI-assisted creation globally accessible. This instant gratification of seeing your project live on the internet provides invaluable experience and reinforces the tangible outcomes of your efforts. Understanding these streamlined publishing workflows empowers you to quickly iterate and share your web projects.\n\n**Case Study**: A student built a personal portfolio website using AI to generate the ''About Me'' text, project descriptions, and initial HTML/CSS structure. They then uploaded their project to Netlify. Within minutes, Netlify automatically built and deployed their site from their GitHub repository, providing a live URL. The student was then able to share their professional-looking portfolio with potential employers, demonstrating both their skills and their ability to leverage modern tools for rapid deployment.',
  learning_objective = 'Successfully deploy a static website created with AI assistance to a chosen free online hosting platform (e.g., Netlify, GitHub Pages), understanding the basic deployment workflow, and making it publicly accessible.',
  practical_task = E'1. **Prepare Your Project**: Take the HTML and CSS files you generated and refined in the previous lesson. Ensure they are organized in a single folder with any images properly linked. 2. **Choose a Hosting Platform**: Select Netlify (recommended for ease) or GitHub Pages. 3. **Deployment**: For Netlify, create an account and drag-and-drop your project folder or connect to a Git repository. For GitHub Pages, create a repository, upload files, and enable Pages in Settings. 4. **Verify and Share**: Test your website in different browsers. Share the live URL along with a short reflection on the ease or challenges of the deployment process.'
WHERE id = '41d059c1-d200-4ddd-9a29-b78ff478743d';